[package]
name = "rslox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
anyhow = { version="1.0.93", features = ["backtrace"]}
phf = { version = "0.11", features = ["macros"] }
